
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LBRACKET = 13;
  public static final int LPAREN = 3;
  public static final int INT = 19;
  public static final int MULTIPY = 29;
  public static final int MINUS = 28;
  public static final int STATIC = 9;
  public static final int RPAREN = 4;
  public static final int NOT = 36;
  public static final int SEMICOLON = 16;
  public static final int AND = 26;
  public static final int LESSTHAN = 27;
  public static final int COMMA = 18;
  public static final int CLASS = 5;
  public static final int PLUS = 2;
  public static final int ASSIGN = 25;
  public static final int MAIN = 11;
  public static final int IF = 21;
  public static final int THIS = 34;
  public static final int DOT = 30;
  public static final int EOF = 0;
  public static final int BOOLEAN = 20;
  public static final int RETURN = 17;
  public static final int RBRACKET = 14;
  public static final int TRUE = 32;
  public static final int NEW = 35;
  public static final int error = 1;
  public static final int VOID = 10;
  public static final int LBRACE = 6;
  public static final int ELSE = 22;
  public static final int WHILE = 23;
  public static final int PUBLIC = 8;
  public static final int RBRACE = 7;
  public static final int EXTENDS = 15;
  public static final int STRING = 12;
  public static final int FALSE = 33;
  public static final int PRINT = 24;
  public static final int LENGTH = 31;
  public static final int INTEGER_LITERAL = 38;
  public static final int IDENTIFIER = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "CLASS",
  "LBRACE",
  "RBRACE",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "STRING",
  "LBRACKET",
  "RBRACKET",
  "EXTENDS",
  "SEMICOLON",
  "RETURN",
  "COMMA",
  "INT",
  "BOOLEAN",
  "IF",
  "ELSE",
  "WHILE",
  "PRINT",
  "ASSIGN",
  "AND",
  "LESSTHAN",
  "MINUS",
  "MULTIPY",
  "DOT",
  "LENGTH",
  "TRUE",
  "FALSE",
  "THIS",
  "NEW",
  "NOT",
  "IDENTIFIER",
  "INTEGER_LITERAL"
  };
}

